[package]
name = "tokei"
version = "1.1.0"
authors = ["Aaronepower <theaaronepower@gmail.com>"]

[profile.dev]
debug = true

[profile.release]
opt-level = 3

[dependencies]
clap = {version = "*", features = ["yaml"]}
glob = "*"
