# Copyright (c) 2015 Aaron Power
# Use of this source code is governed by the MIT/APACHE2.0 license that can be
# found in the LICENCE-{APACHE, MIT} file.
[package]
name = "tokei"
version = "2.1.0"
authors = ["Aaronepower <theaaronepower@gmail.com>"]
repository = "https://github.com/Aaronepower/tokei.git"
homepage = "https://aaronepower.github.io/tokei/"
license = "MIT/Apache-2.0"
readme = "README.md"
description = "Count code, quickly."
build = "build.rs"

# For building serde in stable.
[build-dependencies]
serde_codegen = "0.10.0"
syntex = "0.7.5"

# Dependencies, and why they are used.
# - Clap: For CLI argument parsing.
# - Glob: When a user passes in a ./*.rs path.
# - Maplit: Cleaner initialization of the language map.
# - Rayon: Parallelization of language analysation.
# - Rustc-serialize: Converting String to hex, for CBOR.
# - Serde: Converting Language struct to other formats.
# - Serde_cbor: To CBOR. http://cbor.io/
# - Serde_json: To JSON. http://json.org/
# - Serde_yaml: To YAML. http://yaml.org/
# - Walkdir: Handling recursively reading directories across Windows, OSX, and UNIX.
[dependencies]
clap = {version = "2.5.1", features = ["yaml"]}
glob = "0.2.11"
maplit = "0.1.3"
rayon = "0.3.1"
rustc-serialize = "0.3.19"
serde = "0.7.5"
serde_cbor = "0.3.3"
serde_json = "0.7.0"
serde_yaml = "0.2.4"
walkdir = "0.1.5"
