[package]
authors = ["Aaronepower <theaaronepower@gmail.com>"]
build = "src/lib/build.rs"
description = "A program that allows you to count code, quickly."
homepage = "https://aaronepower.github.io/tokei/"
include = ["src/**/*", "cli.yml", "Cargo.toml", "LICENCE-APACHE", "LICENCE-MIT"]
license = "MIT/Apache-2.0"
name = "tokei"
readme = "README.md"
repository = "https://github.com/Aaronepower/tokei.git"
version = "4.2.0"

[[bin]]
doc = false
name = "tokei"
path = "src/main.rs"

[dev-dependencies]
tempdir = "~0.3.5"

[build-dependencies.serde_codegen]
optional = true
version = "0.8.0"

[dependencies]
glob = "~0.2.11"
maplit = "~0.1.3"
rayon = "~0.4.0"
walkdir = "~0.1.5"

[dependencies.clap]
features = ["yaml"]
version = "~2.10.0"

[dependencies.rustc-serialize]
optional = true
version = "~0.3.19"

[dependencies.serde]
optional = true
version = "~0.8.0"

[dependencies.serde_cbor]
optional = true
version = "~0.3.3"

[dependencies.serde_json]
optional = true
version = "~0.8.0"

[dependencies.serde_yaml]
optional = true
version = "~0.4.0"

[dependencies.toml]
default-features = false
features = ["serde"]
version = "~0.2.0"
optional = true

[features]
all = ["json", "cbor", "toml-io", "yaml"]
cbor = ["io", "rustc-serialize", "serde_cbor"]
default = []
io = ["serde_codegen", "serde"]
json = ["io", "serde_json"]
toml-io = ["io", "toml/serde"]
yaml = ["io", "serde_yaml"]

[lib]
name = "tokei"
path = "src/lib/lib.rs"
