# Copyright (c) 2015 Aaron Power
# Use of this source code is governed by the MIT license that can be
# found in the LICENSE file.
[package]
name = "tokei"
version = "1.3.1"
authors = ["Aaronepower <theaaronepower@gmail.com>"]
repository = "https://github.com/Aaronepower/tokei.git"
homepage = "https://aaronepower.github.io/tokei/"
license = "APACHE(2.0)/MIT"
readme = "README.md"
description = "Count lines of code within a directory, quickly."

[profile.dev]
debug = true

[profile.release]
opt-level = 3

[dependencies]
clap = {version = "1.5.5", features = ["yaml"]}
glob = "0.2.10"
