[package]
authors = ["Aaronepower <theaaronepower@gmail.com>"]
build = "build.rs"
description = "A utility that allows you to count code, quickly."
homepage = "https://github.com/Aaronepower/tokei"
include = ["src/**/*", "languages.json", "build.rs", "cli.yml", "Cargo.toml", "LICENCE-APACHE", "LICENCE-MIT"]
license = "MIT/Apache-2.0"
name = "tokei"
readme = "README.md"
repository = "https://github.com/Aaronepower/tokei.git"
version = "4.5.3"

[build-dependencies]
serde = "~0.8.19"
serde_json = "~0.8.4"
errln = "0.1.0"

[build-dependencies.handlebars]
features = ["serde_type"]
version = "0.21.1"

[build-dependencies.serde_codegen]
optional = true
version = "0.8.19"

[dependencies]
encoding = "~0.2.33"
errln = "0.1.0"
ignore = "~0.1.5"
lazy_static = "~0.2.1"
log = "~0.3.6"
maplit = "~0.1.3"
rayon = "=0.4.2"
regex = "~0.1.80"

[dependencies.clap]
features = ["yaml"]
version = "~2.19.1"

[dependencies.env_logger]
features = []
version = "~0.3.5"

[dependencies.serde]
optional = true
version = "~0.8.19"

[dependencies.serde_cbor]
optional = true
version = "~0.4.0"

[dependencies.serde_json]
optional = true
version = "~0.8.4"

[dependencies.serde_yaml]
optional = true
version = "~0.4.0"

[dependencies.toml]
default-features = false
features = ["serde"]
optional = true
version = "~0.2.1"

[dev-dependencies]
tempdir = "~0.3.5"

[dependencies.hex]
version = "~0.2.0"
optional = true

[features]
all = ["json", "cbor", "toml-io", "yaml"]
cbor = ["io", "hex", "serde_cbor"]
default = []
io = ["serde_codegen", "serde"]
json = ["io", "serde_json"]
toml-io = ["io", "toml/serde"]
yaml = ["io", "serde_yaml"]
