# Copyright (c) 2015 Aaron Power
# Use of this source code is governed by the MIT license that can be
# found in the LICENSE file.
[package]
name = "tokei"
version = "1.1.0"
authors = ["Aaronepower <theaaronepower@gmail.com>"]

[profile.dev]
debug = true

[profile.release]
opt-level = 3

[dependencies]
clap = {version = "*", features = ["yaml"]}
glob = "*"
